### ISSUE TITLE
Requested Changes that haven't been included in the last version

### ISSUE THREAD

**Issue by athmegaritis** [andrejadd/AirExplorer#28]
•	Make sure that a clear MAP is displayed when you access the tool, without any selection in the left panel. The user should then define his/her selection.

**_MAP Viewer – AirBase_**
•	Change the name of “Air Quality Zone” to “Station Area”.
•	In the pop-up windows use units (e.g., μg/m3, ng/m3, etc.) in the different concentrations values.
•	Use dot-markers as default for the AirBase Source
•	For the AirBase Source, add also an option in the left panel to change manually the limit value for a selected pollutant and connect it with the colour that the dot markers appear. We consider this option as really important for the purposes of the tool. 
•	Please add the remaining pollutants in the DB as they were included in the first version of the tool. Only data for SO2 and PM10 appear at the moment.

**_MAP Viewer – E-PRTR_** 
•	Use blue colour for the markers at E-PRTR to avoid misleading. The markers in the AirBase show the compliance picture but in the E-PRTR they just show locations.

•	I would suggest having the following in the left panel:
	After the “Year” box, add another box called “Source Type” with two options to select: 1) “Industrial activity”, 2)  “Economic Sector (NACE)”.
	Below “Source Type”, I suggest having three boxes with the following names: 1) “Sector Name”, 2) “Sector Main Activity” 3) “Sub-Activity”. 

So for example, if you want to check the oil and gas refineries based on the “Industrial activity” type:
1.	you select from the “Sector Name” the “Energy Sector”
2.	This will filter the available activities in the “Sector Main Activity”  and you will select “1.(a) Mineral Oil and gas refineries”.
3.	After this selection, if there are available sub-activities these will be displayed in the “Sub-Activity” (This sub-activity will also solve this issue with the Activity Names that miss some text e.g., “Installations:”) 

Similar structure for NACE selection.

**_Pop-up window for an E-PRTR facility:_**
•	Add the name of the facility. Not only the Facility ID
•	Instead of having separately the Activity Code and the Activity Name, add the following (I am using a refinery as an example):
	Activity Code: e.g. 1.(a) Mineral Oil and Gas Refineries
	NACE Code: 19.20 Manufacture of refined petroleum products
•	Regarding the emissions values:
Now I can see the following (taking SO2, and a facility as an example):
	Pollutant: SOx/S
	Time Point: 2015
	Value: 672000

Can we change it to:
**_	Pollutant: SOx/SO2
	Year: 2015
	Value: 672000 tn
	Method: Measured ?? (Estimated/Calculated)_**

**_E-PRTR Pollutants_**
•	Suggest including the following pollutants of interest
	Benzene
	Carbon dioxide (CO2)
	Carbon monoxide (CO)
	Hydrogen cyanide (HCN)
	Methane (CH4)
	Nitrogen oxides (NOx/NO2)
	Non-methane volatile organic compounds (NMVOC)
	Particulate matter (PM10)
	PCDD + PCDF (dioxins + furans) (as Teq)
	Polycyclic aromatic hydrocarbons (PAHs)
	Sulphur oxides (SOx/SO2)
	Toluene

•	In the pop-up window for the E-PRTR facilities, add the threshold for each pollutant as a solid line in the figure.
•	In the pop-up windows use units (e.g., μg/m3, ng/m3, etc.) in the different emissions values.

Previous Comments (already in GitHub): 

I am copying some of my comments I sent you in GitHub just as a reminder:
	I have noticed that you added each city under the relevant country.
	However, I have also noticed that none of the errors I received when I was trying to create charts were solved. At the moment, I can only create charts for an individual country/city. If I request a more complex chart (e.g., multiple countries, traffic stations, group by country) the chart creator will not create them.
	

- Add an option to select specific time period (specific years)

**Comment by andrejadd** [comment]
I am creating a separate issue for each category (italic bold) above.

* MAP Viewer - Airbase : andrejadd/AirExplorer#32

**Comment by andrejadd** [comment]
E-PRTR pollutants added to import DB script, script needs to be run on server..

**Comment by andrejadd** [comment]
Moved remaining issues to separate issue (measure method, E-PRTR threshold indicator in graph).
Closed
