### ISSUE TITLE
get_user_charts is called multiple times per user after login although it should only be called ones

### ISSUE THREAD

**Issue by andrejadd** [andrejadd/AirExplorer#54]
The load_user() function is called multiple times inside airserver.py after the user logged  in, although it should be only called ones. As an effect the chart and cart container are loaded multiple times. This causes the session to load slower. 

Below is a log starting right after the login:

[this should be the only time these two messages appear, but below are more] 
load_user() ... calling initialise_carts...
get_user_charts() called for user id: 2

127.0.0.1 - - [08/Nov/2018 11:15:14] "GET /charts HTTP/1.1" 200 -
127.0.0.1 - - [08/Nov/2018 11:15:14] "GET /dist/styles.css HTTP/1.1" 200 -
127.0.0.1 - - [08/Nov/2018 11:15:14] "GET /dist/bootstrap.min.css HTTP/1.1" 200 -
127.0.0.1 - - [08/Nov/2018 11:15:14] "GET /dist/bootstrap-slider.min.css HTTP/1.1" 200 -
127.0.0.1 - - [08/Nov/2018 11:15:14] "GET /dist/leaflet.css HTTP/1.1" 200 -
127.0.0.1 - - [08/Nov/2018 11:15:14] "GET /dist/loading-indicator.css HTTP/1.1" 200 -
127.0.0.1 - - [08/Nov/2018 11:15:14] "GET /dist/images/site_busy.gif HTTP/1.1" 200 -
127.0.0.1 - - [08/Nov/2018 11:15:14] "GET /dist/bundle.js HTTP/1.1" 200 -

load_user() ... calling initialise_carts...
get_user_charts() called for user id: 2

127.0.0.1 - - [08/Nov/2018 11:15:15] "GET /data_carts HTTP/1.1" 200 -

load_user() ... calling initialise_carts...
get_user_charts() called for user id: 2

127.0.0.1 - - [08/Nov/2018 11:15:15] "GET /get_user_info HTTP/1.1" 200 -

load_user() ... calling initialise_carts...
get_user_charts() called for user id: 2

127.0.0.1 - - [08/Nov/2018 11:15:16] "GET /get_data_views HTTP/1.1" 200 -

load_user() ... calling initialise_carts...
get_user_charts() called for user id: 2

127.0.0.1 - - [08/Nov/2018 11:15:16] "GET /user_charts HTTP/1.1" 200 -

load_user() ... calling initialise_carts...
get_user_charts() called for user id: 2

127.0.0.1 - - [08/Nov/2018 11:15:16] "GET /get_users HTTP/1.1" 200 -

load_user() ... calling initialise_carts...
get_user_charts() called for user id: 2

**Comment by levvers** [comment]
I'm afraid, this is how FlaskLogin works.
