### ISSUE TITLE
NACE

### ISSUE THREAD

**Issue by levvers** [andrejadd/AirExplorer#58]
I don't understand how the list of NACE Acitivities is being built. I guess it is meant to  contain the NACE Activities for which there is data.

Suppose I select CH4 for 2016 and All NACE Sectors, then I get as NACE Code 01.4.6 Raising of swine/pigs, but the corresponding NACE Activity 01.4 Animal Proiduction is not shown as a NACE Activity, which I think it should be.

**Comment by andrejadd** [comment]
My test on the production server gives following behaviour after I selected *E-PRTR*, *CH3*, *2016* and *Economic Sector (NACE)*:

 - Select *All* in **NACE Sector**: Yields a long list in **NACE Activity**  (all available NACE Activities)
 - Select *All* in **NACE Activites**: Yields a long list in **NACE Code**  (all available NACE Codes)
 - Select *01.4.6 Raising of swine/pigs*: Yields 198 Total Amount (Facilities)

_or_ 

 - Select *All* in **NACE Sector**: Yields a long list in **NACE Activity**  (all available NACE Activities)
 - Select *01.4 Animal production* in **NACE Activites**: Yields *01.4.6* and *01.4.7* in **NACE Code**   
 - Select *01.4.6 Raising of swine/pigs*: Yields 198 Total Amount (Facilities)

Seems to be ok.
