### ISSUE TITLE
Limit values

### ISSUE THREAD

**Issue by levvers** [andrejadd/AirExplorer#59]
I should have picked up this one much earlier, but limits are specific to a pollutant **and** an aggregation. For example for PM10, the limit of 40 is for yearly averages, whereas the limit for daily averages is 50 (the EU allows 35 daily exceedances of 50, but the PM10 value is meant to be below 40. 

Not sure how easy it is to fix this. The easiest wau to address this is to add the settings of a chart a field that allows editing the limit and if no limit is given, no limit is shown.

Thanasis also thinks that SO2 should not have a limit (rather than the value of 20 being used).

**Comment by levvers** [comment]
Resolved in commit fda9a3de9240800733430ca8bcc21c425c3c5c45, except for the default limit of 20 for SO2, which needs to be removed.

**Comment by andrejadd** [comment]
Removed limit from SO2.
Coarse particle -> Coarse particles
