### ISSUE TITLE
Order of pollutants

### ISSUE THREAD

**Issue by levvers** [andrejadd/AirExplorer#63]
Thanasis is unhappy with the order of the pollutants. He would like PM2.5 to appear after NO2 and before PM10.

Shall we introduce a sort-order column in the list of pollutants in the database and then sort the tree by that field (if present). This would make it easy to change the sort-order of the pollutants.

**Comment by andrejadd** [comment]
Added order to map select box and pollutant data cart by adding sortorder column to pollutants. When tree in data cart is build, the sortorder is considered.
