### ISSUE TITLE
Special characters in facility names not handled correctly

### ISSUE THREAD

**Issue by levvers** [andrejadd/AirExplorer#64]
Special characters in facility names do not show correctly

![screenshot from 2018-11-09 23-16-34](https://user-images.githubusercontent.com/26818546/48293220-eb9c5d80-e475-11e8-894c-be293ef67f6c.png)

**Comment by andrejadd** [comment]
Database was in latin1, altered it to utf8mp4

mysql> SELECT default_character_set_name FROM information_schema.SCHEMATA S WHERE schema_name = "airdb";
+----------------------------+
| default_character_set_name |
+----------------------------+
| latin1                     |
+----------------------------+
1 row in set (0.00 sec)

mysql> ALTER DATABASE airdb CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
Query OK, 1 row affected (0.00 sec)

mysql> SELECT default_character_set_name FROM information_schema.SCHEMATA S WHERE schema_name = "airdb";
+----------------------------+
| default_character_set_name |
+----------------------------+
| utf8mb4                    |
+----------------------------+
1 row in set (0.00 sec)

**Comment by andrejadd** [comment]
Added create db instruction to the README:

CREATE DATABASE airdb CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

fixed.
